spring:
  application:
    name: weixing-java

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:xxx/weixin-database?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: xx
    password: xx

# mapper
mybatis:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

##mybaites-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8979